---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpasswd-oci-registry
  namespace: production
spec:
  encryptedData:
    htpasswd: AgBBl2FF4IEyxwBcvPabOgniYDye63bkNVB6KdgRnuWJgB9QwNR2wO5xaRis18tfyzEaX7z5/q90g966q/z0Qi9pmJUx3nftD1Ra1Ms6XaR3X4U0dJzswOZIjSU+7bZm44ZIAWSlYrl1NnYn1gmnE5UDJfQnKPMEUUWwftXI2YSvrKTFtfiu0KXIsheXYPuaR+OORFC1lMTC9NJfxYdFybY9pRD4HipH+RZuDdYI+PaviXYyhKHwblC+AsyQ7TVM5TScy5hZ1dLZYDt20txzhxN0Mj8pRyML1vXtU4Uerm+T0NxIlGFqgueVvkz4HV5h5qv830Ldz4LrLEXSq6Ome+zpyhOlNTMLSGa+DnMf1dFF/5WEqN4QUruivEfE9GGlhv6VCXU4yKBBJJfjj4cBIKUsblAswK6dyYGojZRtABBAHHNtfBBvkf/7u4QvuK5v/eekJ7JJVDofvU1NE91TWNyv049bl26HNR4NRe1C6UdVWNOifMJIL/34Yc1tuQkJyANja2fZ+wBlAKXEm3Os07cLiC3QzxGyD9E72RKDYZA4r2biKkF5/MJHfPpUBu9gTvNeR4lLByRENpUJSZGJbFPK6/FJMoW2wEHmmjm7zmx3wfSLVqJxFvHAiKqEd6xy1tlmqz88lpPXYLafNXqCjzrrkiRwH1eqPzyAIQRv4fcY23ax1FO0SqMmB9wojx+jCcyCWlLD2p6sdMp3lgxcXNgbjw7sqaLZ4DT85GT/fv2Ul3pgsEKTCOSN9cEa/mtxmNDZ9ynnIIRub1VpKqjMT+c2q8RWr8SifQ==
  template:
    metadata:
      creationTimestamp: null
      name: htpasswd-oci-registry
      namespace: production
    type: Opaque
