# self signed issuer
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: production
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oci-registry-cert
  namespace: production
spec:
  secretName: oci-registry-cert
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  subject:
    countries:
      - DE
    province: NRW
    locality: Essen
    organization: OpenTobiCloud
  commonName: docker-auth
  duration: 365d
  renewBefore: 30d
---
apiVersion: batch/v1
kind: Job
metadata:
  name: transform-cert-secret
  namespace: production
spec:
  template:
    spec:
      containers:
      - name: transform-secret
        image: bitnami/kubectl:latest
        command: ['sh', '-c']
        args:
          - |
            set -e;
            CERT=$(kubectl get secret docker-registry-cert -n production -o jsonpath="{.data.tls\.crt}" | base64 -d | base64);
            kubectl create secret generic your-docker-registry-cert -n production --from-literal=tokenAuthRootCertBundle=$CERT --dry-run=client -o yaml | kubectl apply -f -;
      restartPolicy: OnFailure
