kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: che-cluster-clusterrolebinding
  namespace: eclipse-che
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
subjects:
- kind: ServiceAccount
  name: che-operator
  namespace: eclipse-che
roleRef:
  kind: ClusterRole
  name: che-cluster-clusterrole
  apiGroup: rbac.authorization.k8s.io