apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: che-cluster-tls-cert
  namespace: eclipse-che
spec:
  secretName: che-cluster-tls-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - che.open-tobi-cloud.com
  usages:
    - digital signature
    - key encipherment