apiVersion: v1
kind: ConfigMap
metadata:
  name: mydashboard-mobile
  labels:
    kubenav.io/prometheus: dashboard
data:
  charts: |
    - title: 'temp'
      unit: '°C'
      queries:
        - query: 'node_hwmon_temp_celsius'
