apiVersion: v1
kind: ConfigMap
metadata:
  name: mydashboard-mobile
  labels:
    kubenav.io/prometheus: dashboard
data:
  charts: |
    - title: 'HTTP Requests'
      unit: 'req/s'
      queries:
        - label: '{{.response_code}}'
          query: 'sum(rate(nginx_ingress_controller_requests{namespace="default"}[1m])) by (response_code)'
          legendFormat: '{{.response_code}}'
          color: '#FF0000'
