commonLabels:
  heritage: gitops
crds:
  enabled: false

grafana:
  ingress:
    enabled: true
    pathType: Prefix
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - monitoring.open-tobi-cloud.com
    tls:
      - secretName: grafana-tls
        hosts:
          - monitoring.open-tobi-cloud.com

prometheusOperator:
  admissionWebhooks:
    certmanager:
      enabled: true
  #   deployment:
  #     resources:
  #       requests:
  #         cpu: 100m
  #         memory: 128Mi
  #       limits:
  #         cpu: 500m
  #         memory: 512Mi
  #   patch:
  #     resources:
  #       requests:
  #         cpu: 100m
  #         memory: 128Mi
  #       limits:
  #         cpu: 500m
  #         memory: 512Mi
  # resources:
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi
  #   limits:
  #     cpu: 500m
  #     memory: 512Mi
  # prometheusConfigReloader:
  #   resources:
  #     requests:
  #       cpu: 100m
  #       memory: 128Mi
  #     limits:
  #       cpu: 1000m
  #       memory: 512Mi
