resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 512Mi
controller:
  ingressClassResource:
    name: "gitea-nginx"
  ingressClass: "gitea-nginx"
  scope:
    enabled: true
    namespace: "production"
  tcp:
    annotations:
      "gitea-ingress"
installCRDs: false