image:
  tag: "1.21.11"
  rootless: true
redis-cluster:
  enabled: false
postgresql:
  enabled: false
postgresql-ha:
  enabled: false
gitea:
  config:
    database:
      DB_TYPE: "postgres"
      HOST: "gitea-rw"
      NAME: gitea
    server:
      DOMAIN: "git.open-tobi-cloud.com"
    session:
      PROVIDER: "memory"
    log:
      LEVEL: "Debug"
  oauth:
    - name: "keycloak"
      provider: "openidConnect"
      existingSecret: "gitea-keycloak-client-secret"
      autoDiscoverUrl: "https://auth.open-tobi-cloud.com/realms/master/.well-known/openid-configuration"
      requiredClaimName: "groups"
      groupClaimName: "groups"
      adminGroup: "Gitea-Admin"
      restrictedGroup: "Gitea-User"
  additionalConfigFromEnvs:
    - name: GITEA__DATABASE__USER
      valueFrom:
        secretKeyRef:
          name: gitea-db-auth-secret
          key: username
    - name: GITEA__DATABASE__PASSWD
      valueFrom:
        secretKeyRef:
          name: gitea-db-auth-secret
          key: password
service:
  http:
    type: "LoadBalancer"
    annotations:
      "metallb.universe.tf/allow-shared-ip": "https://git.open-tobi-cloud.com"
  ssh:
    type: "LoadBalancer"
    annotations:
      "metallb.universe.tf/allow-shared-ip": "https://git.open-tobi-cloud.com"
    labels:
      # part of ingress controller
      "app.kubernetes.io/part-of": "gitea-nginx"
ingress:
  enabled: true
  className: "gitea-nginx"
  annotations:
    "cert-manager.io/cluster-issuer": "letsencrypt-production"
    "nginx.ingress.kubernetes.io/proxy-body-size": "1g"
  hosts:
    - host: "git.open-tobi-cloud.com"
      paths:
        - path: "/"
          pathType: "Prefix"
  tls:
    - secretName: "gitea-cert"
      hosts:
        - "git.open-tobi-cloud.com"
persistence:
  enabled: true
  size: "10Gi"
securityContext:
  capabilities:
    add:
      - "SYS_CHROOT"
