apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
  annotations:
    argocd.argoproj.io/sync-wave: "2"