---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: act-runner-secret
  namespace: production
spec:
  encryptedData:
    token: AgCWXn99pXh9p5LVzmFxyDJ1R/BrixDnaKVTssCWSsV6avDaC2chpCSokHsheibbbAAjR5Zy7ncr5iepjx6KvmeY7D71/QD5h/yp29CVxDhmDctKY1INKL38hPCPKDpGHgYsFO4HMpgvtlFLTcpBWp5cgqvwD/vA8BUi0pJa21MDCUM0DF9XspMsZd/jzQ3OtwtQUH48PVm2QJ95ifRJUUdfrxbb7mk8JU+g6xUX34+jDfDooaCkyH42RhRePMhBWmfhr/vqLAQWxNxHPTQQif2MdOqFxrMDYECkx0Hdf+PGfWKVaWkLDv4fi9c9d6oa0e9HS0TufdfaE4LZdnyvsdq7v78g+1n9o0MBe9eaWZS+0ZbZeJVWt0q+u1dUNtI5P3Qe9TjtTOWag3s51GjiIUfrAmczOc0E/PCoVPXArTBEYqj1JfjIgUIg+OBz/Zc5/sZzWGRdD6cRdzf8hJfS3aS47Fz74bve2X/V5yhE9W3TkLC9ZGrfGYKIU4VoblGmkiZf8lEbgVmpFBLOpmKDvP/Bu38ie8F7aaid+JGw6LSGsMGwy38bJIEs3nHnqHa0DV8c95Zxvjauze+j3a6lfLRtA4Kd0ecIxf01MnG2ahcXQmVkw+XPhBs8Uap3VoyxEYxiBXQ1wuMZoBdBi7zjZ18t2zIXxHQ7a8URimJltfxVqhc/VwDoe/h8KU8ERBnmnkIhfnZ8LQCVHuFRZ4p6MGVwY8CYOn6SzNQqXKqseqk=
  template:
    metadata:
      creationTimestamp: null
      name: act-runner-secret
      namespace: production
    type: Opaque
