---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: act-runner-secret
  namespace: production
spec:
  encryptedData:
    token: AgA4bhipS/DeQv045p0ATbSWkU4bC89Ig5lTW1mCj4qSxDKaJ4ZE9DyS0o+uGHQeqolcxalmCQue8G82VZAj6OpCZcztrfm7pLQ71q8VNeM6bRSaPhgMPX5kqVN/XdutJPUHQrIxUm580v0CZG0ztcaaTvX4BuKjVGjiCGHOiqSaysvhoskGUfcFP+537OkVpQOq7iRMHafnI63r+I7uB9YpdnqwJnC+4cc9P5Ki2yMwGbws1F8/dfn+eV3ws8Tk+Aqur+fC9zvvoF+1juaMBVKG1Yvurx7MQFJbttd3C8rcW8zGc6lxEnEU2c59Y9tAmu8PJdx9Wb9A+PO7+B6tpvSRQaLlZRigGpd6/FckPtmQQ2Vy3xcZYqE9fuRDTkypypGncMXeUGS1XVAkoPWcJdHiW65yUuXWtWjalTytQkeXVOHC6pXYLBszOMcKpPh1EPZhMj+3iwoku/LAWORv3qZYz+mzr8fh55HKRo/pMBZ4LhWcs50+vFRvabaG5GOCoJiqc2tSROwuZC6nyDbF+18aHGKPWjaMKIDmcSe587rgSioHq6/PUG4sB1/0vUIR2mfioo86rF5tcoLNUnLUw+X+RO9PYlSVovu1r8CgTnoNSMC5TME+Ay91LwvK8q817g8Q82nOQejwul2GJ8fITq/urwc3RVGWTMPlMTgJFuI9Nx5RydsCrXjyPSuEx+nVnfdIpKKt1RdLXaTl8BgA+nczSEubOpwH/OTexQ7wMDDbcDiXZ1EUMLcj
  template:
    metadata:
      creationTimestamp: null
      name: act-runner-secret
      namespace: production
    type: Opaque
