---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: act-runner-secret
  namespace: production
spec:
  encryptedData:
    token: AgBzYos72ufhtxq5FeJdy5bfvKn6xZYX4re88dbiu6TXXsuM2+QGnfFukqcZ2XPBEtVuZlEt4HMvvPHNykSJ2I75avR8lMUYvrXPnrZpf1VD/FvFjSqdybd9udloiIqbLwzYbXxFJTY7DqhO7uy8QvYPQKlPqYTKfgzIo8FrFodNlaBVXTCOeWtsDVMznLFoG7IjsCEQSL4E0StE5+sh8bsNThjAmnJUyHkkkSGaBgM/EWCgBg+x98YPYWc3MxiOhsyqzhqvtm6Zdd7lzJEUy5kFioOhHf+YRQcP4TxGupBx3hjqTi+NWl0qItpBGRFrWQWdkY6Qe/Hhz6SAY71cOvcjoau6sUfvrjZRgB9FB7jmHiEo0hgWaZrYlon/0i+jENU6UXA9YbVmBOe/MfwgcuY56Vi6LoNcfkZ4tVJDgoRdotOSGC89rHGM9pPBmakRcH1R7dLHwd8MADUNPmIgsqSuhpLht4LynugIwvAbz8twlk8jo0GXw5pdMK4+NSusSBbLjFGzw2MUe2ArF4jmpS7SxNpYsHxuN+eMpKUrTdQt5efY5MJgj/gbwLQCn241C3iskO/lQGVeJOojtHzTAHDv06zggZ1V4RAMaDWtNTvaZd9t/vMXWakJ38/Lmb+KGLj+Q9NOxabAPGuuGMusUjzTiUURifhVkiJ1pNzb0DISouyn5MbYP2vnSg1HvUbUReOoQOh6rPFZL0cdb5vlDyEwyXn9fGNjdsG1Jne34318QJHD/Bk7wnST
  template:
    metadata:
      creationTimestamp: null
      name: act-runner-secret
      namespace: production
    type: Opaque
