---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: act-runner-secret
  namespace: production
spec:
  encryptedData:
    token: AgBaGzKwXeqfAt8Cud+TOuu+RIYMLNHu43HfDQJLhuGizTmcU1F4pG599oarJHhZlQxRvr2v9PRcN/L/GVis8AJ2y92xB1B4UlJlqwgxcqYYc2aGYqxly0WvGcZ5HNZuqsk3oy8x1bmvfSJcMI84/sAfbEViAMACqH905h1N4lamEnx2EvpHOKVy2PmDx0Eby5ykv6IoaKUHg2jkAj0VLcu6vTtiqNgcMN71kcSIdBWpGMW9QECltW4E+AMAIxLLp9ngSPwRbD9KuCEfMJk29DMEFGDE02GieZ/48Hqa+vnE2Ryv7jke0VuS3Oi9Gu8bNlkahlJnf8T7EBHKXNwsvL1PEu/tZ/n1K7Jx95/2vK5jYzxrNWGPJntyDY4uLgJL78Yz6LR6bESWZlhzTzfN7vACt594I3mYjbCLdAJKyuu2ErtRXi06gauccINjNLUQD3HUAHMmQQot/4Qz6eiCxRLxai+MBqN8jAVRJBW43JiX2+cO3c6K176v6hBtuandMfyZVsOGBlKgwhkNHE+iI3gfxtYAh55Qtq5nkOPen7bkDZKNhO36+On00XGNrtDXBlefBhZlTeJP3y3xb6A5OKO0XcmmMrC0vNMOr/hPrYQnYhAe+GXisEJrvhpD2R47pIA3bA3rQyqms8LkGnqvj0lBG7v9EZqQ9mSGAVXJCsS+igiLHH2hDRNm/NQo0Uk/mU3xmw84HQEMvuUwAGVPMQE3oRMa6BSOrL55qcg9nME=
  template:
    metadata:
      creationTimestamp: null
      name: act-runner-secret
      namespace: production
    type: Opaque
