---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: eclipse-che-keycloak-secret
  namespace: production
spec:
  encryptedData:
    key: AgBtQpRUwiRS0/+d7kaCWQuLpujGnb1VdB1+C3Wr3sgDUUtKtagLFvaK5LLke4gi2yURINyL8C4HnlntrQofx3Oe/7QkOwwqSbq8IAe5jkuL5kWEgFq258PsSJviIWXm8Yr86tBNure8dCYGwLxeV1dKz0K7Y4M31dNOsHEpaCkY4mW2wI2q2jHgsWEI5sfoWIT4Qup/LDBcvVjrPWukfIkvXQDJRQQUGnsAv/sWm7GFDOMRZTW4QvIa6bdNPEpd8qKH22nw9XEXLkcLzd3dxZvJTzbKumTTUhuyBcoWwb079qOrbJZYqH9MYwF8gCIKNW5+J84DThFgmwgRjsOSQKeas7DvBhDVklLXXkALHbml6MEQw1/pbfzEaA3o1wgI4z3JNWg+02YR/NhFlivmp9UwSZsCKyGucWZK4ZzCSsYc+9YHimGsDQkSex9eHdeH1WQ6ss0QUA5Rj3fCmJh1z8IOHIDGQrD4JsL2zWszlu334XGRcbPFXYdla0mSDYJoqvEFVKAsOGQY/Df53MdVjplTCCwvcWhQRqKXPjKmuhAxRoWfo+17bPN+jfOoGzrogWM0iNOzi23Fne6c4dmiftMFlcU14CWbjL4+ruWLbIYwCUStJAI2Ae0h72JykXBwrUTg1Fm5BYLb1qDRjI5s1LpwasKMvVm5Y+3XOgbWuwKo9KYa0DnwjQRewepVo9wojHBxCyvwxHsd+n4wtg==
    secret: AgBvr/liwd5RS/KXhsJIGwqPPBA0v9K1WO+733+GmErg4bHRqfzvWIkpDIzGbbSEVFj3apPP8Vu+5AQDTSrPhGyTqbVF4RgfmHS8L/fMJQUMpaRm+HFp5fc0oL8qlohsZWAm44r6ABCHm0AA4uIlBy9nUUf+MpIZCGNUu0k0AVuU409sMLYCtwYTW95F4/zbvATBaT301etupGcJacINb/SOfBjd6UujFTHQ9HeUKO4R2LVTB0VexAskeHA9LaC7AXiNSVte3ecRvSyetAh2GeRTHmkeV8DPWefFPEpyjemQLcakcOXyhG7u7Ti6U8DdKsKZmwwFRbtJeGfoRAnatK9Nq2Tt0T18wNyNVg3X4LzAYbEV/LeOxhUd9h4cjsUZ1ia47pnIua4yQbrO5Sl3RgEqtGG/tKVWRU3fz7DOIEhIQOxDBe75tNXr3bgYeWTyFrcDDlyVA+H5LXeuXBjAbPbR37ypSvhS56TfXBpRF4SWoWZCMCEfg9qhbL38WOWyzjBYR1e/cU3MA//FBwKb8zPdif9k6fU65z97vomf1qnri8vTKPns3knUhQe90b8JtkzlZ62JSjNE92fmdlr5NA/Q/MjrOAGJKawRKtieCbQ5vb3pPmdCfMBEn6OfteTUIfZSyjoqbEMvP7v9qK7xgF8in5NBy29yhjzcwgOXxIoiYJD35wNiArXM0BYmmRcwmfBkomhA79WFtRgJ0a3WM5+2R7RFnPx1vgymjUTTpnUHxA==
  template:
    metadata:
      creationTimestamp: null
      name: eclipse-che-keycloak-secret
      namespace: production
    type: Opaque
