apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-parent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/TKlauenberg/cloud-gitops.git'
    targetRevision: HEAD
    path: apps/gitea
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    automated: {}
operation:
  sync:
    prune: true