apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitea
spec:
  instances: 5
  bootstrap:
    initdb:
      database: gitea
      secret:
        name: gitea-db-auth-secret
  storage:
    size: 10Gi
    storageClass: "nfs-csi-client"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
