apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitea
spec:
  instances: 2
  bootstrap:
    initdb:
      database: gitea
      secret:
        name: gitea-db-auth-secret
  storage:
    size: 10Gi
# resources:
#   requests:
#     cpu: 100m
#     memory: 128Mi
#   limits:
#     cpu: 500m
#     memory: 512Mi