apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default
  source:
    chart: gitea
    repoURL: "https://dl.gitea.io/charts"
    targetRevision: 9.6.1
    helm:
      valueFiles:
        - conf/values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated: {}
