---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-db-auth-secret
  namespace: production
spec:
  encryptedData:
    password: AgB0QFqpNpu7ymX7eBKqajHSIPctvmuDJSJAifui3QQC0QIvz66W1X7ksZqY6qlfJWiAI/jtRjtcdGHJhiw7dSpPeFydi7PB+KZxYYOdSunZpSmQWeFh9grI00HaQr4B6fs9E1nr8z3FHDhCmpJOYv42LFc+cfsOLpL7D4VmT6SMdxfxHKoTpzVG6aD/G1hhex497q2svujmrEupKzbW6qZLQZigKwQXIW+kVhBh7iQhIwC86ugDW0HQsfYopqUTlPGWCBfesjn/T/O7r2LxADqYwrnAyd3ktlJHvAWwFoYL0ffrRTCVVomm41Jv/5n768mpWITblCbYUKhfOOwIIzbshW7+8DjEtFRrCW2wLcoUm01ai2fDV5k91zTXDFrwODpXG/NjgAkSnsIia0SU73JCYHoJmUjkJpfJphLhI8NgyOKpjH9FwArWKucJ1A1dilQdEg3+w6fDe8zKaQ+XJaXbXd5ki56XhsFMr9IBHiLAoAFMKP33fK3j9T8CLWvY9EvWLcTnTXWzPHNbrfPgOO0yWTxlz4orbhw8PfKZ3+HZD1ont5AvJL3K63Q+h//By1MKBYz82uo4u82fKIj914UQRS6pqSj48eVcxGoSJ2IZOgmUAbuZG/3xpINvBfJkGTMfMJFJjlqRHYoINMRQH5WWsHlECYiBjPjqjN/5Hj9tT7xSa1Vm+USk/p+dzbEJDbA9FZmeoFJThJO3
    username: AgCcPDX9sNGVbjwVFC7zjXYOHWDmZTBxYrEb3JERUk0LWFWxtVEgpVMyRvWhNfFQ2EiVmMokNy0OI6KuDng2OZjC4UuL+iHuYwUnlIsrSrm8B9YtRt7Yzt+chEDyEd0D1VGjqd84zLAq1tjjv88CjJdnqm4TsVFfciaHHmguZ0+crQUM94ccKxDue7uvPLXp9lFtPtDMoeK8sZBf4E2Ahzcrx9Pp1ITBDwWFQ++Y/UHJXqiP+jhN4RshQZC/vbs4Ke4hvoIJCF98a4vuLYhdWJC1Q7Gl+kMDa3IZ4Bc3v8Ih8ItwEyewr/McQINr5z1ftHTDxFV6ALuUhW2faSMuZLAVz8z8CC9SH1CM+SY2jCQD+1GKJIKSZ/Ry7Sih1xd1eCgWhhwulsaYX2/Uz3rJCCq2I16HBpMz2bL1cHjo+Fl7FkdQiEYg6WGmk+WUAXXA6ur523AqxTwp+2W8KDrJJzOP134WcVLXYq4/mMG3j/ERL7y+D4Z5KZo47zxLvBqdh7szbjZ7g31d+wJeGC/1Y2LWDQ/HiLOSGJu+UQBbnz6QgTteLLfMvH28n0pzlKDcQZbT6rMje9mYIkUWK0b+oQp7zftIbUx9XFXdKyWjpBdmH/PVbPaHns/LkSWJkLZd1E1UgNHW0BkoM8xteyGhRI0XtzajbcDHw1PNWsuLS+tKmiUhlqnZH9xfhZxFgJisiMq3Yu3Pj5w=
  template:
    metadata:
      creationTimestamp: null
      name: gitea-db-auth-secret
      namespace: production
    type: kubernetes.io/basic-auth
