---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-db-auth-secret
  namespace: production
spec:
  encryptedData:
    password: AgBz+gKhf98gMfDcYisg+YOkdlHbuRXXDx8Bc4PH85jZu3xebAow1uS8ZzAWdmak5BdU+3woI6t+5EUaln58ZOlB/g5IRi509GCpF6XxlZilOa5kF73Qzwh1Z7mbHDcGWBci1F3gsD87MVKu/P3RST9RJZpWpQk7tcQ2eIHJdV+P7cMD+usYriYeshDBOndtFiVXJIPO0ogylDmH19TJaSeSUJ37/snb2Dz/bHS2NQxbERttr1aS6g3QTkr4lPCkxtkCguIwlbvRo/rC4lGLoZo57uZJCf9WJ8idVgE+wd6DPYYRoPL/XKJrwbfkca+oYAoRbzSK0NllG706LLwUsyTLSEfXCsrq8dLw/+kH+PHnnuQaXP1yfFlghr6boJm5SyQPYfatI5LLQ+T83gS76J0JAwkg/9WyK3iw4ytOMXYCaiVzSanPYRsAPx61/Y4tvSNmnkkIwzUs+8Cvi652mWotcveAbNM72l44fHmV3J/d773eIx+1ySX7Grn/vEdsgFEYKs+OkSfAoeFltsApJ8O90i51UysOkN3+AA57vSRF8wU1qqrhFYJt6swCKYi4ErzYZSqxt3lFAkIL/w7/QxtXt8Du3RK9HCzCZBTe03Inu9FK2bQflUWmiCDHNaFUgXHhdzxcvE5hSAnmFXncCOzDngY++TiR2aj7EJwdr/G3GFYYw6AjH7uSsk4C+ohSNCC2VpPQ1ZWurrR/
    username: AgAFnc/Ibjc9jkaUbjDnX0EivMPNKbV2D2EHGS2ZJ5/+V9liPjl9PS7o9/twEbUqiCYR87Eic+jK81qzhTA0OtudUpXgNNlYjsVlFGF24PrmZTYnr0EJaM6PbEGBOafocjn1qxdO90KFJdgGU+CewMJLNCVRkwYITWaIeXCz15cICziQWe8IRq9uaxYuxu7ekFv0+s/ZcC7frtJewxEbnJWEUREvMIYHk8H8wFMOJgEO9+LaliHcwfNGTGLicTDaHAHqIkxKxO3HTJFG5ccJXiBseqxUszDtPCUnEN/BwCtJK+sEcNSanBInxAsQABe7oxrKfraWEc9vVFOcsl2oEJaUHbMkxX+4Xhh7OMpQOc8T7XFbNt8yMncb5wb9O11rrri0z4H4W/aogCOlU/8C0KRpWdlsBZw2QlKqj/KLtVU07gjU6QeNW5aSEayM5sHUuFoWYAVJ++MUp5NxTZXBud1wnIDfrSH1atu6xMbOM5XPyI3w98kCbq0uLOwHBMewMQvWSzSTk3Krg3VbASGIS8v1Vcy9SSdYYW9xV1XzY+H9StA4ZuZsSaIHbhjAp+aEp6kG4bXd/+t4dy1m46VPwb+xrrOGr3jlOE02ZogYsIqVb0XBvxjbOIrlBpTNvB4F7UlUVTlVJKZLD92LMt6+kL067MeoLa/0N5LK32ZhDpq0qHeYR2tCGcdFDKVsq1xX3XAXA1oWVA==
  template:
    metadata:
      creationTimestamp: null
      name: gitea-db-auth-secret
      namespace: production
    type: kubernetes.io/basic-auth
