---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-keycloak-client-secret
  namespace: kube-system
spec:
  encryptedData:
    key: AgC0Q2IJ/lVr7zgw0Z2Vu4ObcpY8z1Ea2KF2p2Wbp/vYznU66fTrL7ZxM8Wugdvd0ao2t6LnmjocMRvlUOjpRcADCc1OAgendsEOwCa9Pa04DXOtANA9TkSyQrcZ7K0q2TpFyEwBZPG+k5EXnnPVuNrEDFw5A8BUu2ywLuEP17MKf67qI0Asx1i/EuVqF8ppIJMv6r1C8NZ+NaYZ9pkL7889BJtNGLta/MMVHIVV2vcNzItSp/J7Edc9eTXV/PMfUFysClELCfVnp7EqYG9Op5d5EFshrInSpz43wBtk1caKsjwzx6QfJWROpHih7oElIRpTBV6QlKkqRd4OONdehWUpaInAmLmMe9xVztXhxb7MgDjKMA+BKKS+nTThdx7UaRWdoPAVzL+mzYMWUhFhLQwn98vLhKrojdxUOAiamlrP/Lk7M1QEJ0byXAnqdW6dGixemw/SMaPdfE99iAGNsObiagPtGcFMdIIIxHIp9Z9EP2zIGJVmKP2qYOOuLVnqDKQjtpuvqh3hm5yk4jIO61apx2P4y5X7Fq0U1/Pe0CkNkag/X5hCu1ExMykOdXavqCCCwDsB4HAZ0xAIWfsyxfpT54BLOZ4sdwumg2y6YxggHpiTDX8pnVMv8lDdWqWHRN3Q0GfTBlq0vKq7DzWUIhtmz5EvC2eMM7WbJJqtc7v7dd8puHPyzcUbLbV40dSC8y/q0wxImA==
    secret: AgChWzabcJiZHn6UTH+mCViGUV+GNN5196+Sj4j1Ip6729pJtgW/ICPldKfEfdDrh0wCbBhDvLdpBl2hou2KaE4XtQlCWGeayQqZ4wl/E9RpnvSsiuyqGcuRVuyxEFw6SL8trK4sR50Ci1EIS+DUl96z6lHO1Ue6U/LK9RnhCUkUqmYGwaCMbGEWti6ILzqw2tFE+h5X+3r+jGYQ9menrSnYUIo8f83BNd3aRNwpwEtcQi3JIfr8+YQty60zdwZaTRqi0BPqvUxn6MmB/NgLkPfgU01BIvczUfNQJLzPkKrn3L8EONuIMKUynuswWrHQl2n9oKzakmfyVAKAI9f1Zu5K0pbCeND/1FvpeJNuIujNvck+aQeARaWYfSIfgQ85NI5pq48Bw/4i6G1lO8Gw0X4maVNv/ug+0i0dSY4yoFWUW5VP7wy5HWU0UaxkLpF/XiRElubWsrQfodNpMHlA0RGHEEMErTw+/B+OBPQJvLSGf9pO2L168Dp3nHEFoIPMYjkgRApqmWIACAqtYGRa7JUW7H9pBT8ZuxYZ62VA2jmNaNtxd9EZneBcUrDFph0fdj+UWA+1CZPNN7gFDG/PTpH+vQJ3vhih0tzdMrhqj0LWzH6InMnuhyqATCM2UR6lFHpeLf3GVCHvhG5GJ6iBfn6GKKvilfvMOD+U87hGmCTPsDPrIUjMCfbNNtgIehlfKWnO62V4xn9X7edBwYY9Ex4XLmCB+tikkeIGjlGaI8i6xw==
  template:
    metadata:
      creationTimestamp: null
      name: gitea-keycloak-client-secret
      namespace: kube-system
    type: Opaque
